export type DefenseCommercialUnit = "USD_PER_KG" | "USD_PER_TON" | "USD_PER_UNIT" | "USD_PER_THOUSAND_UNITS" | "USD_PER_PAIR" | "USD_PER_SQUARE_METER" | "AD_VALOREM";
export type DefenseCommercialExporterOption = { exporter: string; rate: number; unit: DefenseCommercialUnit; collectionSuspended?: boolean; };
export type DefenseCommercialMeasure = { ncm: string; product: string; origins: string[]; measure: "antidumping"; legalFoundation: string; source: string; validityNote: string; exportersByOrigin: Record<string, DefenseCommercialExporterOption[]>; };
const normalize = (value: string) => value.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
export const DEFENSE_COMMERCIAL_MEASURES: DefenseCommercialMeasure[] = [
  {
    ncm:"40112090", product:"Pneus de carga de construção radial", origins:["China","Coreia do Sul","Japão","Rússia","Tailândia"], measure:"antidumping",
    legalFoundation:"Resolução GECEX nº 198/2021; Resolução GECEX nº 176/2021; Resolução GECEX nº 540/2023; Circular SECEX nº 20/2026", source:"MDIC/SECEX — Medidas em vigor: Pneus de carga", validityNote:"Medida mantida em vigor durante revisão de final de período.",
    exportersByOrigin:{
      china:[
        {exporter:"Shandong Linglong Tyre Co., Ltd.",rate:1.05,unit:"USD_PER_KG"},{exporter:"Triangle Tyre Co., Ltd.",rate:1.07,unit:"USD_PER_KG"},{exporter:"Zhongce Rubber Group Co., Ltd.",rate:1.12,unit:"USD_PER_KG"},{exporter:"Double Coin Holdings Ltd.",rate:1.12,unit:"USD_PER_KG"},{exporter:"Giti Tire (Anhui) Co., Ltd.",rate:1.31,unit:"USD_PER_KG"},{exporter:"Giti Tire (Chongqing) Company Ltd.",rate:1.31,unit:"USD_PER_KG"},{exporter:"Giti Tire (Fujian) Company Ltd.",rate:1.31,unit:"USD_PER_KG"},{exporter:"Aeolus Tyre Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Chaoyang Long March Tyre Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Cooper Chengshan (Shandong) Tire Company Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Guangming Tyre Group Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Jiangsu Hankook Tire Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Michelin Shenyang Tire Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Pirelli Tyre Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Sailun Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Sailun Jinyu Group Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Shandong Jinyu Tire Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Shandong Changfeng Tyres Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Shandong Hengyu Rubber Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Shandong Longyue Rubber Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Shandong Wanda Boto Tyre Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Shenyang Peace Radial Tyre Manufacturing Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Shouguang Firemax Tyre Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Sinotyre International Group Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Triangle (Weihai) Huamao Rubber Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Zhaoqing Junhong Co., Ltd.",rate:1.42,unit:"USD_PER_KG"},{exporter:"Shandong Bayi Tyre Manufacture Co., Ltd.",rate:1.55,unit:"USD_PER_KG"},{exporter:"Demais empresas",rate:2.59,unit:"USD_PER_KG"}],
      "coreia do sul":[{exporter:"Kumho Tires Co. Inc.",rate:0.32,unit:"USD_PER_KG"},{exporter:"Hankook Tire Co., Ltd.",rate:0.51,unit:"USD_PER_KG"},{exporter:"Demais empresas",rate:1.49,unit:"USD_PER_KG"}],
      japao:[{exporter:"Sumitomo Rubber Industries",rate:0.21,unit:"USD_PER_KG",collectionSuspended:true},{exporter:"Demais empresas",rate:1.59,unit:"USD_PER_KG",collectionSuspended:true}],
      russia:[{exporter:"OAO Cordiant",rate:1.10,unit:"USD_PER_KG"},{exporter:"Demais empresas",rate:0.72,unit:"USD_PER_KG"}],
      tailandia:[{exporter:"Zhongce Rubber Co. Ltd",rate:0.55,unit:"USD_PER_KG"},{exporter:"Demais empresas",rate:0.53,unit:"USD_PER_KG"}]
    }
  },
  {
    ncm:"70191290", product:"Fibras de vidro do tipo E e/ou E-CR (roving)", origins:["China","Egito"], measure:"antidumping",
    legalFoundation:"Resolução GECEX nº 960, de 2 de setembro de 2026, DOU de 04/09/2026", source:"MDIC/SECEX — Medidas em vigor: Fibras de vidro", validityNote:"Direito antidumping provisório vigente até 04/03/2027.",
    exportersByOrigin:{
      china:[
        {exporter:"Jushi Group Co., Ltd",rate:456.44,unit:"USD_PER_TON"},{exporter:"Jushi Group Chengdu Co., Ltd",rate:456.44,unit:"USD_PER_TON"},{exporter:"Jushi Group Jiujiang Co., Ltd",rate:456.44,unit:"USD_PER_TON"},{exporter:"Taishan Fiberglass Inc",rate:211.78,unit:"USD_PER_TON"},{exporter:"Taishan Fiberglass Zibo Inc.",rate:211.78,unit:"USD_PER_TON"},{exporter:"Taishan Fiberglass Zoucheng Inc",rate:211.78,unit:"USD_PER_TON"},{exporter:"Chongqing Polycomp International Corp. (Cpic)",rate:456.44,unit:"USD_PER_TON"},{exporter:"Amp Composites Co Limited",rate:426.47,unit:"USD_PER_TON"},{exporter:"Anquiu Industry Co; Ltd",rate:426.47,unit:"USD_PER_TON"},{exporter:"Chang Zhou Matex Composites Co., Ltd",rate:426.47,unit:"USD_PER_TON"},{exporter:"Changshu Dongyu Insulated Compound Materials Co.,Ltd",rate:426.47,unit:"USD_PER_TON"},{exporter:"Changshu Dyf International Trading Co., Ltd",rate:426.47,unit:"USD_PER_TON"},{exporter:"Changzhou Pro-Tech Trade Co.,Ltd.",rate:426.47,unit:"USD_PER_TON"},{exporter:"Changzhou Utek Composite Co., Ltd",rate:426.47,unit:"USD_PER_TON"},{exporter:"Changzhou Zhongjie Composites Co.,Ltd.",rate:426.47,unit:"USD_PER_TON"},{exporter:"Cnbm International Corporation",rate:426.47,unit:"USD_PER_TON"},{exporter:"Huierjie New Material Technology Co., Ltd",rate:426.47,unit:"USD_PER_TON"},{exporter:"Jiangxi Meta Technology Development Co., Ltd",rate:426.47,unit:"USD_PER_TON"},{exporter:"Jiujiang Beihai Fiberglass Co., Ltd.",rate:426.47,unit:"USD_PER_TON"},{exporter:"Qingdao Joint Chemicals Co., Ltd",rate:426.47,unit:"USD_PER_TON"},{exporter:"Shanghai Orisen New Materials Technology Co., Ltd.",rate:426.47,unit:"USD_PER_TON"},{exporter:"Shanghai Sanviz Technical Services Co Ltd",rate:426.47,unit:"USD_PER_TON"},{exporter:"Sichuan Chang Yang Composites Company Limited",rate:426.47,unit:"USD_PER_TON"},{exporter:"Svasia Limited Co.",rate:426.47,unit:"USD_PER_TON"},{exporter:"Utek-Dele Technology Changzhou Co., Ltd",rate:426.47,unit:"USD_PER_TON"},{exporter:"Weiyuan Beshine Trading Co., Ltd",rate:426.47,unit:"USD_PER_TON"},{exporter:"Yw-Huhe Trading Company",rate:426.47,unit:"USD_PER_TON"},{exporter:"Demais empresas",rate:456.44,unit:"USD_PER_TON"}],
      egito:[{exporter:"Jushi Egypt For Fiberglass Industry S.A.E.",rate:243.42,unit:"USD_PER_TON"},{exporter:"Demais empresas",rate:243.42,unit:"USD_PER_TON"}]
    }
  }
];
export function findDefenseCommercialMeasure(ncm:string,origin:string,importDate?:string){const normalizedNcm=ncm.replace(/\D/g,"");const normalizedOrigin=normalize(origin);const measure=DEFENSE_COMMERCIAL_MEASURES.find(candidate=>candidate.ncm===normalizedNcm&&candidate.origins.some(item=>normalize(item)===normalizedOrigin));if(!measure)return undefined;return{...measure,importDate};}
export function listDefenseCommercialExporters(ncm:string,origin:string,importDate?:string){const measure=findDefenseCommercialMeasure(ncm,origin,importDate);if(!measure)return null;const options=measure.exportersByOrigin[normalize(origin)]??[];return{measure,options};}
export function resolveDefenseCommercialExporter(ncm:string,origin:string,exporter?:string,importDate?:string){const result=listDefenseCommercialExporters(ncm,origin,importDate);if(!result)return undefined;const normalizedExporter=normalize(exporter??"");if(!normalizedExporter)return result.options.find(option=>normalize(option.exporter)==="demais empresas")??result.options.at(-1);return result.options.find(option=>normalize(option.exporter)===normalizedExporter);}
