import fs from "node:fs";
import path from "node:path";
import { DEFENSE_COMMERCIAL_MEASURES as LEGACY_DEFENSE_COMMERCIAL_MEASURES, type DefenseCommercialExporterOption, type DefenseCommercialMeasure, type DefenseCommercialUnit, type DefenseCommercialMeasureType } from "./defesa-comercial-catalog.ts";
const generatedData=JSON.parse(fs.readFileSync(path.join(process.cwd(),"data","defesa-comercial-mdic.json"),"utf8"));
const validityAuditData=JSON.parse(fs.readFileSync(path.join(process.cwd(),"data","defesa-comercial-validity-audit-2026.json"),"utf8"));
const auditedOverridesData=JSON.parse(fs.readFileSync(path.join(process.cwd(),"data","defesa-comercial-audited-overrides-2026.json"),"utf8"));
const auditedOverridesWave3Data=JSON.parse(fs.readFileSync(path.join(process.cwd(),"data","defesa-comercial-audited-overrides-2026-09-07-wave3.json"),"utf8"));
export const normalize=(value:string)=>value.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[\*,:;]+$/g,"").trim();
const ORIGIN_ALIASES:Record<string,string>={"coreia":"coreia do sul","coréia":"coreia do sul","coreia do sul":"coreia do sul","japao":"japao","japão":"japao","taipé chines":"taipe chines","taipe chines":"taipe chines","eua":"estados unidos da america","estados unidos":"estados unidos da america","united states":"estados unidos da america","united states of america":"estados unidos da america","estados unidos da america":"estados unidos da america","republica popular da china":"china","da china":"china","do reino da tailandia":"tailandia","reino da tailandia":"tailandia","tailandia":"tailandia","da malasia":"malasia","malasia":"malasia","uniao europeia":"uniao europeia"};
export const normalizeOrigin=(value:string)=>ORIGIN_ALIASES[normalize(value)]??normalize(value);
type GeneratedMeasure=DefenseCommercialMeasure&{ncmPatterns?:string[];ncmExclusions?:string[];sourceUrl?:string;collectionSuspended?:boolean;validUntil?:string;importDate?:string;continuationAfterNominalExpiry?:boolean;validityAuditLegalBasis?:string;requiresScopeValidation?:boolean;scopeCondition?:string};
type ValidityAuditEntry={product:string;sourceUrl:string;nominalValidUntil:string;disposition:"continuation_review"|"renewed";effectiveValidUntil?:string;legalBasis:string};
const generated=(Array.isArray(generatedData)?generatedData:[]) as unknown as GeneratedMeasure[]; const auditedOverrides=(Array.isArray(auditedOverridesData?.entries)?auditedOverridesData.entries:[]) as unknown as GeneratedMeasure[]; const auditedOverridesWave3=(Array.isArray(auditedOverridesWave3Data?.entries)?auditedOverridesWave3Data.entries:[]) as unknown as GeneratedMeasure[]; const validityAuditEntries=(Array.isArray(validityAuditData?.entries)?validityAuditData.entries:[]) as ValidityAuditEntry[]; const validityAuditBySource=new Map(validityAuditEntries.map(e=>[e.sourceUrl,e]));
const SCOPE_VALIDATION_BY_SOURCE:Record<string,string>={
 "https://www.gov.br/mdic/pt-br/assuntos/comercio-exterior/defesa-comercial-e-interesse-publico/medidas-em-vigor/medidas-em-vigor/esteres-aceticos":"A medida não se aplica aos produtos acondicionados em embalagens com capacidade não superior a 4 litros.",
 "https://www.gov.br/mdic/pt-br/assuntos/comercio-exterior/defesa-comercial-e-interesse-publico/medidas-em-vigor/medidas-em-vigor/batatas-congeladas":"É necessário validar a descrição e apresentação do produto contra as exclusões de escopo da medida antes de aplicar o direito automaticamente."
};
const OFFICIAL_INACTIVE_ORIGINS:Record<string,string[]>={"https://www.gov.br/mdic/pt-br/assuntos/comercio-exterior/defesa-comercial-e-interesse-publico/medidas-em-vigor/medidas-em-vigor/tubos-de-coleta-de-sangue":["alemanha"],"https://www.gov.br/mdic/pt-br/assuntos/comercio-exterior/defesa-comercial-e-interesse-publico/medidas-em-vigor/medidas-em-vigor/laminados-planos-de-baixo-carbono-e-baixa-liga-chapas-grossas":["africa do sul"],"https://www.gov.br/mdic/pt-br/assuntos/comercio-exterior/defesa-comercial-e-interesse-publico/medidas-em-vigor/medidas-em-vigor/pneus-de-carga":["china"]};
const OFFICIAL_REGRESSION_OVERRIDES:GeneratedMeasure[]=[{ncm:"23099090",ncmPatterns:["23099090","29224110","29224190"],ncmExclusions:[],product:"Lisina",origins:["China"],measure:"antidumping",legalFoundation:"RESOLUÇÃO GECEX Nº 923, DE 24 DE JUNHO DE 2026; RETIFICAÇÃO - RESOLUÇÃO GECEX Nº 923, DE 24 DE JUNHO DE 2026",source:"MDIC/SECEX — Medidas de defesa comercial em vigor",sourceUrl:"https://www.gov.br/mdic/pt-br/assuntos/comercio-exterior/defesa-comercial-e-interesse-publico/medidas-em-vigor/medidas-em-vigor/lisina-md",validityNote:"Prazo de vigência: 25/06/2031",validUntil:"25/06/2031",collectionSuspended:false,exportersByOrigin:{china:[{exporter:"Jilin Meihua Amino Acid Co., Ltd.e Xinjiang Meihua Amino Acid Co., Ltd.",rate:78,unit:"AD_VALOREM"},{exporter:"Ningxia Eppen Biotech Co., Ltd.; Inner Mongolia Eppen Biotech Co. Ltd.; Heilongjiang Eppen Biotech Co. Ltd.",rate:26,unit:"AD_VALOREM"},{exporter:"Qiqihar Longjiang Fufeng Biotechnologies Co., Ltd.",rate:41.3,unit:"AD_VALOREM"},{exporter:"Shouguang Golden Corn Biotechnological Co., Ltd.",rate:54.5,unit:"AD_VALOREM"},{exporter:"Demais empresas chinesas",rate:132.6,unit:"AD_VALOREM"}]}},{ncm:"28353920",ncmPatterns:["28353920"],ncmExclusions:[],product:"Pirofosfato ácido de sódio (SAPP)",origins:["Canadá","Estados Unidos da América"],measure:"antidumping",legalFoundation:"Resolução CAMEX Nº 67 – DOU de 15/08/2014; Resolução GECEX no. 50 - DOU de 15/06/2020; Resolução CAMEX Nº 903, DOU de 08/06/2026; Circular SECEX Nº 40, DOU de 09/06/2026",source:"MDIC/SECEX — Medidas de defesa comercial em vigor",sourceUrl:"https://www.gov.br/mdic/pt-br/assuntos/comercio-exterior/defesa-comercial-e-interesse-publico/medidas-em-vigor/medidas-em-vigor/pirofosfato-acido-de-sodio-sapp",validityNote:"Prazo de vigência: 08/06/2031",validUntil:"08/06/2031",collectionSuspended:false,exportersByOrigin:{"canadá":[{exporter:"Innophos Canada Inc.",rate:546.3,unit:"USD_PER_TON"},{exporter:"Demais",rate:1066.3,unit:"USD_PER_TON"}],"estados unidos da américa":[{exporter:"Innophos Inc.",rate:418.13,unit:"USD_PER_TON"},{exporter:"Prayon Inc.",rate:734.28,unit:"USD_PER_TON"},{exporter:"Demais",rate:734.28,unit:"USD_PER_TON"}]}}];
export const DEFENSE_COMMERCIAL_MEASURES:GeneratedMeasure[]=[...generated,...auditedOverrides,...auditedOverridesWave3,...OFFICIAL_REGRESSION_OVERRIDES,...LEGACY_DEFENSE_COMMERCIAL_MEASURES].map(measure=>{const condition=measure.sourceUrl?SCOPE_VALIDATION_BY_SOURCE[measure.sourceUrl]:undefined;return condition?{...measure,requiresScopeValidation:true,scopeCondition:condition}:measure;});
export {type DefenseCommercialExporterOption,type DefenseCommercialMeasure,type DefenseCommercialUnit,type DefenseCommercialMeasureType};
function optionsForOrigin(measure:GeneratedMeasure,origin:string){const entry=Object.entries(measure.exportersByOrigin).find(([o])=>normalizeOrigin(o)===origin);return entry?.[1]??[];} function inactive(measure:GeneratedMeasure,origin:string){return Boolean(measure.sourceUrl&&(OFFICIAL_INACTIVE_ORIGINS[measure.sourceUrl]??[]).some(o=>normalizeOrigin(o)===origin));}
function matchingMeasures(ncm:string,origin:string){const nn=ncm.replace(/\D/g,"");return DEFENSE_COMMERCIAL_MEASURES.filter(c=>{const match=c.ncm===nn||c.ncmPatterns?.some(p=>nn===p||nn.startsWith(p));const excluded=c.ncmExclusions?.some(x=>x===nn);return Boolean(match&&!excluded&&!inactive(c,origin)&&c.origins.some(o=>normalizeOrigin(o)===origin));});}
function scopeIdentity(m:GeneratedMeasure){return m.sourceUrl?`official:${m.sourceUrl}`:`fallback:${normalize(m.product)}|${normalize(m.legalFoundation??"")}`;} function distinctScopes(c:GeneratedMeasure[]){const official=c.some(x=>Boolean(x.sourceUrl));const seen=new Set<string>();return c.filter(x=>{if(official&&!x.sourceUrl)return false;const id=scopeIdentity(x);if(seen.has(id))return false;seen.add(id);return true;});}
function mergedOptions(c:GeneratedMeasure[],origin:string){const seen=new Set<string>();const out:DefenseCommercialExporterOption[]=[];for(const m of c)for(const raw of optionsForOrigin(m,origin)){if(/^[0-9.,]+$/.test(String(raw.exporter??"").trim()))continue;const sig=`${normalize(raw.exporter)}|${raw.rate}|${raw.unit}|${Boolean(raw.collectionSuspended)}`;if(!seen.has(sig)){seen.add(sig);out.push({...raw});}}return out;}
function applyValidityAudit(m:GeneratedMeasure):GeneratedMeasure{if(!m.sourceUrl)return m;const a=validityAuditBySource.get(m.sourceUrl);if(!a)return m;if(a.disposition==="renewed"&&a.effectiveValidUntil)return{...m,validUntil:a.effectiveValidUntil,validityNote:`Prazo de vigência auditado: ${a.effectiveValidUntil}`,continuationAfterNominalExpiry:false,validityAuditLegalBasis:a.legalBasis};return{...m,continuationAfterNominalExpiry:a.disposition==="continuation_review",validityAuditLegalBasis:a.legalBasis};}
export function listMatchingDefenseCommercialScopes(ncm:string,origin:string){const no=normalizeOrigin(origin);return distinctScopes(matchingMeasures(ncm,no)).map(c=>{const a=applyValidityAudit(c);return{product:a.product,legalFoundation:a.legalFoundation,sourceUrl:a.sourceUrl,validUntil:a.validUntil};});}
export function findDefenseCommercialMeasure(ncm:string,origin:string,importDate?:string){const no=normalizeOrigin(origin),candidates=matchingMeasures(ncm,no);if(!candidates.length)return undefined;const scopes=distinctScopes(candidates),ambiguous=scopes.length>1;const pool=!ambiguous&&scopes.length===1?candidates.filter(c=>scopeIdentity(c)===scopeIdentity(scopes[0])):(scopes.length?scopes:candidates);const raw=[...pool].sort((a,b)=>optionsForOrigin(b,no).length-optionsForOrigin(a,no).length)[0];const selected=applyValidityAudit(raw),merged=mergedOptions(candidates,no);return{...selected,importDate,scopeAmbiguous:ambiguous,collectionSuspended:!ambiguous&&merged.length?false:selected.collectionSuspended,matchingScopes:scopes.map(c=>{const a=applyValidityAudit(c);return{product:a.product,sourceUrl:a.sourceUrl,legalFoundation:a.legalFoundation,validUntil:a.validUntil};}),exportersByOrigin:{...selected.exportersByOrigin,[no]:ambiguous?optionsForOrigin(selected,no):merged}};}
export function listDefenseCommercialExporters(ncm:string,origin:string,importDate?:string){const no=normalizeOrigin(origin),c=matchingMeasures(ncm,no);if(!c.length)return null;const measure=findDefenseCommercialMeasure(ncm,no,importDate);if(!measure)return null;const scopes=distinctScopes(c),ambiguous=scopes.length>1;return{measure,ambiguous,matchingScopes:scopes.map(x=>{const a=applyValidityAudit(x);return{product:a.product,sourceUrl:a.sourceUrl,legalFoundation:a.legalFoundation,validUntil:a.validUntil};}),options:ambiguous?[]:mergedOptions(c,no)};}
export function resolveDefenseCommercialExporter(ncm:string,origin:string,exporter?:string,importDate?:string){const result=listDefenseCommercialExporters(ncm,origin,importDate);if(!result||result.ambiguous)return undefined;const ne=normalize(exporter??"");if(!ne)return result.options.find(o=>/demais|todas as empresas|todos os produtores/i.test(o.exporter))??result.options.at(-1);return result.options.find(o=>normalize(o.exporter)===ne);}
