import { findDefenseCommercialMeasure, resolveDefenseCommercialExporter, type DefenseCommercialUnit, type DefenseCommercialMeasureType } from "./defesa-comercial-registry.ts";

export type ExtendedDefenseCommercialUnit = DefenseCommercialUnit | "USD_PER_PAIR" | "USD_PER_SQUARE_METER";
export type DefenseCommercialInput = { ncm: string; origin: string; importDate: string; weightKg?: number; quantity?: number; areaM2?: number; exporter?: string; exchangeRate?: number; customsValueBrl?: number };
export type DefenseCommercialResolution = {
  status: "not_applicable" | "identified" | "requires_input";
  measure?: DefenseCommercialMeasureType;
  product: string; ncm: string; origin: string; unit?: ExtendedDefenseCommercialUnit; rate?: number; rateUsdPerKg?: number; amountBrl?: number; exporter?: string;
  exporterTreatment: "default_other_companies" | "specific_company" | "requires_validation"; collectionSuspended?: boolean; legalFoundation: string; source: string; sourceUrl?: string; validUntil?: string; continuationAfterNominalExpiry?: boolean;
  requiresScopeValidation?: boolean; scopeCondition?: string; warnings: string[];
};
type GeneratedMeasureMetadata = { sourceUrl?: string; collectionSuspended?: boolean; scopeAmbiguous?: boolean; validUntil?: string; continuationAfterNominalExpiry?: boolean; requiresScopeValidation?: boolean; scopeCondition?: string; matchingScopes?: Array<{ product: string; sourceUrl?: string; legalFoundation?: string; validUntil?: string }> };
function normalizeText(value?: string) { return String(value ?? "").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[\*,:;]+$/g, "").trim(); }
function measureLabel(measure?: DefenseCommercialMeasureType) { return measure === "countervailing" ? "Medida compensatória" : "Medida antidumping"; }
function effectiveMeasureSuspension(metadata: GeneratedMeasureMetadata, origin: string) { if (metadata.sourceUrl?.endsWith("/pneus-de-carga")) return normalizeText(origin) === "japao"; return Boolean(metadata.collectionSuspended); }
function ddmmyyyyToIso(value?: string) { const match=String(value??"").match(/^(\d{2})\/(\d{2})\/(\d{4})$/); if(!match)return undefined; const iso=`${match[3]}-${match[2]}-${match[1]}`; const date=new Date(`${iso}T00:00:00Z`); return Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==iso?undefined:iso; }
function isIsoDate(value?: string) { if(!/^\d{4}-\d{2}-\d{2}$/.test(String(value??"")))return false; const date=new Date(`${value}T00:00:00Z`); return !Number.isNaN(date.getTime())&&date.toISOString().slice(0,10)===value; }
function calculateAmountBrl(unit:ExtendedDefenseCommercialUnit,rate:number,input:DefenseCommercialInput,exchange:number){if(unit==="AD_VALOREM"){const v=Number(input.customsValueBrl);return Number.isFinite(v)&&v>0?v*(rate/100):undefined;}const q=Number(input.quantity),w=Number(input.weightKg),a=Number(input.areaM2);if(unit==="USD_PER_KG")return Number.isFinite(w)&&w>0?w*rate*exchange:undefined;if(unit==="USD_PER_TON")return Number.isFinite(w)&&w>0?(w/1000)*rate*exchange:undefined;if(unit==="USD_PER_THOUSAND_UNITS")return Number.isFinite(q)&&q>0?(q/1000)*rate*exchange:undefined;if(unit==="USD_PER_PAIR"||unit==="USD_PER_UNIT")return Number.isFinite(q)&&q>0?q*rate*exchange:undefined;if(unit==="USD_PER_SQUARE_METER")return Number.isFinite(a)&&a>0?a*rate*exchange:undefined;return undefined;}
function requirementForUnit(unit:ExtendedDefenseCommercialUnit){switch(unit){case"USD_PER_KG":case"USD_PER_TON":return"informe o peso líquido para calcular este componente";case"USD_PER_THOUSAND_UNITS":case"USD_PER_PAIR":case"USD_PER_UNIT":return"informe a quantidade para calcular este componente";case"USD_PER_SQUARE_METER":return"informe a área em m² para calcular este componente";case"AD_VALOREM":return"o valor aduaneiro é necessário para calcular este componente";default:return"informe os dados necessários para calcular este componente";}}
export function resolveDefenseCommercial(input:DefenseCommercialInput):DefenseCommercialResolution{
 const ncm=input.ncm.replace(/\D/g,""); const measure=findDefenseCommercialMeasure(ncm,input.origin,input.importDate); if(!measure)return{status:"not_applicable",product:"",ncm,origin:input.origin,exporterTreatment:"requires_validation",legalFoundation:"",source:"",warnings:[]};
 const metadata=measure as typeof measure&GeneratedMeasureMetadata; const suspended=effectiveMeasureSuspension(metadata,input.origin); const label=measureLabel(measure.measure); const expiry=ddmmyyyyToIso(metadata.validUntil); const validDate=isIsoDate(input.importDate); const past=Boolean(validDate&&expiry&&input.importDate>expiry);
 const base={measure:measure.measure,product:measure.product,ncm,origin:input.origin,collectionSuspended:suspended,legalFoundation:measure.legalFoundation,source:measure.source,sourceUrl:metadata.sourceUrl,validUntil:metadata.validUntil,continuationAfterNominalExpiry:Boolean(metadata.continuationAfterNominalExpiry),requiresScopeValidation:Boolean(metadata.requiresScopeValidation),scopeCondition:metadata.scopeCondition};
 if(metadata.requiresScopeValidation){return{...base,status:"requires_input",exporterTreatment:"requires_validation",warnings:[`${label} identificada para NCM ${ncm} originária de ${input.origin}.`,measure.validityNote,metadata.scopeCondition?`A aplicação depende de validação do escopo do produto: ${metadata.scopeCondition}`:"A aplicação depende de validação adicional do escopo do produto.","Nenhum valor de defesa comercial foi calculado automaticamente."].filter(Boolean)};}
 if(past&&!metadata.continuationAfterNominalExpiry)return{...base,status:"requires_input",exporterTreatment:"requires_validation",continuationAfterNominalExpiry:false,warnings:[`${label} identificada para NCM ${ncm} originária de ${input.origin}.`,measure.validityNote,`A vigência nominal registrada terminou em ${metadata.validUntil} e não há continuidade pós-vigência auditada no catálogo. Nenhum valor foi calculado automaticamente; valide a situação jurídica atual na fonte oficial.`].filter(Boolean)};
 const resolved=resolveDefenseCommercialExporter(ncm,input.origin,input.exporter,input.importDate); if(!resolved){const ambiguity=metadata.scopeAmbiguous?`Mais de um escopo de produto/medida coincide com a NCM ${ncm} e a origem ${input.origin}. Nenhum valor foi calculado automaticamente.`:"A medida oficial foi localizada, mas a matriz de produtor/exportador e direito aplicável não pôde ser resolvida automaticamente.";return{...base,status:"requires_input",exporterTreatment:"requires_validation",warnings:[`${label} identificada para NCM ${ncm} originária de ${input.origin}.`,measure.validityNote,past&&metadata.continuationAfterNominalExpiry?"A continuidade da medida durante revisão de final de período foi auditada para esta fonte oficial.":"",ambiguity].filter(Boolean)};}
 const exchange=Number(input.exchangeRate??0);const warnings=[`${label} identificada para NCM ${ncm} originária de ${input.origin}.`,measure.validityNote].filter(Boolean);if(past&&metadata.continuationAfterNominalExpiry)warnings.push("A continuidade da medida durante revisão de final de período foi auditada para esta fonte oficial.");const residual=/demais|todas as empresas|todos os produtores/i.test(resolved.exporter);if(residual&&!input.exporter?.trim())warnings.push(`Sem produtor/exportador informado; foi usada provisoriamente a categoria residual (${resolved.rate} na unidade da medida).`);else if(residual)warnings.push(`O produtor/exportador informado não possui tratamento individual cadastrado; aplica-se a categoria residual (${resolved.rate} na unidade da medida).`);else warnings.push(`Direito de defesa comercial resolvido para o produtor/exportador selecionado: ${resolved.rate} na unidade da medida.`);if(resolved.collectionSuspended||suspended)warnings.push("A cobrança da medida está suspensa para esta origem; o direito é identificado, mas não compõe o valor a recolher enquanto a suspensão estiver vigente.");if(!Number.isFinite(exchange)||exchange<=0)warnings.push("Câmbio necessário para converter o direito de US$ para R$.");const unit=resolved.unit as ExtendedDefenseCommercialUnit;const amount=calculateAmountBrl(unit,resolved.rate,input,exchange);if(amount===undefined)warnings.push(`Direito com unidade ${unit}; ${requirementForUnit(unit)}.`);const can=amount!==undefined&&(unit==="AD_VALOREM"||(Number.isFinite(exchange)&&exchange>0))&&!resolved.collectionSuspended&&!suspended;return{...base,status:can?"identified":"requires_input",unit,rate:resolved.rate,rateUsdPerKg:unit==="USD_PER_KG"?resolved.rate:undefined,amountBrl:can?amount:undefined,exporter:resolved.exporter,exporterTreatment:residual?"default_other_companies":"specific_company",collectionSuspended:Boolean(resolved.collectionSuspended||suspended),warnings};
}
