import { calculateSCMultiItemFinalCost, type SCMultiItemFinalCostResult } from "./sc-multi-item-final-cost-engine.ts";
import { resolveSCBenefit, type SCBenefitResolution } from "./sc-benefit-resolution.ts";

export type ImportScenario = "normal" | "ttd409" | "ttd410" | "ttd77";
export type ImportScenarioInput = { ncm:string; quantity:number; fobUnitUsd:number; exchangeRate:number; freightUsd:number; insuranceUsd:number; otherExpensesBrl:number; iiRate:number; ipiRate:number; pisImportRate:number; cofinsImportRate:number; icmsRate:number; importDate?:`${number}-${number}-${number}`; destination?:"commercial_resale"|"industrialization"|"same_holder_transfer"; industrializationInSC?:boolean; taxableOutput?:boolean; preservesOriginalCharacteristics?:boolean; sameNcmPosition?:boolean; exclusionKnown?:boolean; otherDeferment?:boolean; paragraph23Or24?:boolean; equivalentTaxableEventElection?:boolean };
export type ImportScenarioResult = { scenario:ImportScenario; label:string; legallyEligible:boolean; decision:"apply"|"conditional"|"deny"|"normal"; legalReasons:string[]; blockingIssues:string[]; source:string; normalImportICMS:number; effectiveImportICMS:number; importICMSSavings:number; landedCostBeforeBenefit:number; landedCostAfterBenefit:number; landedCostPerUnit:number; engineResult:SCMultiItemFinalCostResult; benefitResolution?:SCBenefitResolution };
const LABELS:Record<ImportScenario,string>={normal:"Regime normal",ttd409:"TTD 409",ttd410:"TTD 410",ttd77:"TTD 77"};
function buildItem(i:ImportScenarioInput){return {itemId:"comparison-item",customsValue:(i.quantity*i.fobUnitUsd+i.freightUsd+i.insuranceUsd)*i.exchangeRate,quantity:i.quantity,iiRate:i.iiRate,ipiRate:i.ipiRate,pisImportRate:i.pisImportRate,cofinsImportRate:i.cofinsImportRate,icmsRate:i.icmsRate,importDate:i.importDate};}
export function compareImportScenario(input:ImportScenarioInput,scenario:ImportScenario):ImportScenarioResult{const item=buildItem(input);const expenses=[{id:"other-expenses",description:"Outras despesas",amount:input.otherExpensesBrl,treatment:"operational_cost" as const,allocation:"item_value" as const}];const base=calculateSCMultiItemFinalCost({items:[item],expenses});if(scenario==="normal"){const r=base.items[0];return {scenario,label:LABELS[scenario],legallyEligible:true,decision:"normal",legalReasons:["Sem benefício estadual selecionado; cálculo tributário normal preservado."],blockingIssues:[],source:"Motor tributário SC + Federal",normalImportICMS:r.normalImportICMS,effectiveImportICMS:r.normalImportICMS,importICMSSavings:0,landedCostBeforeBenefit:r.landedCostBeforeBenefit,landedCostAfterBenefit:r.landedCostBeforeBenefit,landedCostPerUnit:r.landedCostBeforeBenefit/input.quantity,engineResult:base};}const ttd=Number(scenario.replace("ttd","")) as 77|409|410;const benefit=resolveSCBenefit({ttd,destination:input.destination??"commercial_resale",ncm:input.ncm,exclusionKnown:input.exclusionKnown,taxableOutput:input.taxableOutput,industrializationInSC:input.industrializationInSC,preservesOriginalCharacteristics:input.preservesOriginalCharacteristics,sameNcmPosition:input.sameNcmPosition,otherDeferment:input.otherDeferment,paragraph23Or24:input.paragraph23Or24,equivalentTaxableEventElection:input.equivalentTaxableEventElection,normalOutputICMS:0});const engine=benefit.decision==="apply"?calculateSCMultiItemFinalCost({items:[item],expenses,benefitsByItem:{"comparison-item":benefit}}):base;const r=engine.items[0];return {scenario,label:LABELS[scenario],legallyEligible:benefit.decision==="apply",decision:benefit.decision,legalReasons:benefit.reasons,blockingIssues:benefit.blockingIssues,source:benefit.source,normalImportICMS:r.normalImportICMS,effectiveImportICMS:r.benefitImportICMS,importICMSSavings:r.importICMSSavings,landedCostBeforeBenefit:r.landedCostBeforeBenefit,landedCostAfterBenefit:r.landedCostAfterBenefit,landedCostPerUnit:r.landedCostPerUnitAfterBenefit,engineResult:engine,benefitResolution:benefit};}
export function compareImportScenarios(input:ImportScenarioInput){return (["normal","ttd409","ttd410","ttd77"] as ImportScenario[]).map(s=>compareImportScenario(input,s));}
