export type ScImportExemption = {
  id: string;
  article: string;
  status: 'mapped_needs_catalog' | 'mapped_rule' | 'expired_or_revoked_check';
  effectiveFrom?: string;
  effectiveTo?: string;
  productCriteria?: string[];
  beneficiaryCriteria?: string[];
  operationCriteria: string[];
  federalCondition?: string[];
  specialConditions?: string[];
  requiresAuthorization?: boolean;
  requiresSimilarCheck?: boolean;
  legalBasis: string[];
  source: string;
};

/**
 * Import exemptions are intentionally represented as individual rule families.
 * They must never be collapsed into a generic "import exemption" flag.
 * NCM/Anexo-1 lists and temporal conditions are versioned dependencies.
 */
export const SC_IMPORT_EXEMPTIONS: ScImportExemption[] = [
  { id:'SC-EX-ART3-I-ALADI-FRESH-FRUIT', article:'Anexo 2 art. 3 I', status:'mapped_rule', productCriteria:['frutas frescas','origem ALADI','exceções: amêndoa, avelã, castanha, maçã, noz, pêra'], operationCriteria:['entrada importada'], legalBasis:['RICMS/SC Anexo 2 art. 3 I'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-II-BREEDING-STOCK', article:'Anexo 2 art. 3 II', status:'mapped_rule', productCriteria:['matriz/reprodutor bovino, ovino, suíno ou bufalino','puro de origem ou puro por cruza'], operationCriteria:['entrada em estabelecimento comercial ou produtor','registro genealógico oficial possível'], legalBasis:['RICMS/SC Anexo 2 art. 3 II'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-VIII-EMBRAPA', article:'Anexo 2 art. 3 VIII', status:'mapped_rule', operationCriteria:['importação direta pela EMBRAPA','pesquisa científica/tecnológica','financiamento por empréstimos internacionais firmados pelo Governo Federal'], legalBasis:['RICMS/SC Anexo 2 art. 3 VIII','Convênio ICMS 64/95'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-IX-MEDICAL-PUBLIC', article:'Anexo 2 art. 3 IX', status:'mapped_needs_catalog', productCriteria:['máquinas, aparelhos, equipamentos e instrumentos médico-hospitalares/técnico-científicos','sem similar nacional'], beneficiaryCriteria:['órgãos/entidades públicas','fundações/entidades beneficentes elegíveis'], operationCriteria:['entrada direta do exterior','ensino, pesquisa ou serviços médico-hospitalares'], federalCondition:['isenção/alíquota zero de II ou IPI'], specialConditions:['comprovação de similaridade conforme regra vigente','vigência do convênio'], requiresAuthorization:true, requiresSimilarCheck:true, legalBasis:['RICMS/SC Anexo 2 art. 3 IX','Convênio ICMS 104/89'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-X-MEDICAL-PARTS-REAGENTS-MEDS', article:'Anexo 2 art. 3 X', status:'mapped_needs_catalog', productCriteria:['partes/peças','reagentes químicos','medicamentos da Seção X do Anexo 1','sem similar nacional, ressalvadas hipóteses'], beneficiaryCriteria:['órgãos/entidades públicas','fundações/entidades beneficentes elegíveis'], operationCriteria:['entrada direta do exterior','pesquisa médico-hospitalar/ensino/serviços médico-hospitalares'], federalCondition:['isenção/alíquota zero de II ou IPI'], specialConditions:['certificação de similaridade quando exigida','doação e Lei 8.010 possuem exceções específicas','despacho fiscal quando exigido'], requiresAuthorization:true, requiresSimilarCheck:true, legalBasis:['RICMS/SC Anexo 2 art. 3 X','Convênio ICMS 104/89'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XI-CASAN', article:'Anexo 2 art. 3 XI', status:'mapped_rule', beneficiaryCriteria:['CASAN'], operationCriteria:['concorrência internacional','projeto de saneamento básico','financiamento internacional de longo prazo','participação de indústria nacional'], federalCondition:['isenção/alíquota zero de II ou IPI'], legalBasis:['RICMS/SC Anexo 2 art. 3 XI','Convênio ICMS 42/95'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XII-PUBLIC-STATE', article:'Anexo 2 art. 3 XII', status:'mapped_needs_catalog', productCriteria:['mercadoria sem similar nacional'], beneficiaryCriteria:['administração pública estadual direta, autarquias ou fundações'], operationCriteria:['ativo imobilizado, uso ou consumo'], specialConditions:['atestado de inexistência de similaridade, com exceção para importações Lei 8.010'], requiresSimilarCheck:true, legalBasis:['RICMS/SC Anexo 2 art. 3 XII','Convênio ICMS 48/93'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XIII-DONATION-PUBLIC-CHARITY', article:'Anexo 2 art. 3 XIII', status:'mapped_rule', beneficiaryCriteria:['órgãos/entidades públicas','fundações/entidades beneficentes elegíveis'], operationCriteria:['doação direta do exterior','sem contratação de câmbio','uso nos objetivos-fim'], federalCondition:['isenção/alíquota zero de II ou IPI'], requiresAuthorization:true, legalBasis:['RICMS/SC Anexo 2 art. 3 XIII','Convênio ICMS 80/95'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XIV-PUBLIC-SCIENTIFIC-IT', article:'Anexo 2 art. 3 XIV', status:'mapped_needs_catalog', productCriteria:['equipamentos científicos/informática, partes, peças, acessórios, reagentes','sem similar nacional'], beneficiaryCriteria:['órgãos da administração pública direta/indireta'], operationCriteria:['uso nos objetivos-fim'], federalCondition:['isenção/alíquota zero de II ou IPI'], requiresAuthorization:true, requiresSimilarCheck:true, legalBasis:['RICMS/SC Anexo 2 art. 3 XIV','Convênio ICMS 80/95'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XV-BLOOD', article:'Anexo 2 art. 3 XV', status:'mapped_rule', beneficiaryCriteria:['órgãos/entidades de hematologia e hemoterapia públicos, sem fins lucrativos'], operationCriteria:['fracionamento/industrialização de sangue ou embalagem/acondicionamento/recondicionamento'], federalCondition:['isenção/alíquota zero de II'], legalBasis:['RICMS/SC Anexo 2 art. 3 XV','Convênio ICMS 24/89'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XVI-APAE', article:'Anexo 2 art. 3 XVI', status:'mapped_needs_catalog', productCriteria:['produtos da Seção XXXIX do Anexo 1','sem similar nacional'], beneficiaryCriteria:['APAE'], operationCriteria:['importação direta'], requiresSimilarCheck:true, legalBasis:['RICMS/SC Anexo 2 art. 3 XVI','Convênio ICMS 41/91'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XVII-DONATION-FREE-DISTRIBUTION', article:'Anexo 2 art. 3 XVII', status:'mapped_needs_catalog', beneficiaryCriteria:['instituição educacional ou assistência social'], operationCriteria:['doação por organização internacional/estrangeira ou país estrangeiro','distribuição gratuita em programa implementado pela instituição'], legalBasis:['RICMS/SC Anexo 2 art. 3 XVII'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XX-FREE-SHOPS', article:'Anexo 2 art. 3 XX', status:'mapped_rule', beneficiaryCriteria:['lojas francas em cidades gêmeas autorizadas'], operationCriteria:['entrada/recebimento para comercialização'], specialConditions:['vigência do Convênio ICMS 91/91 e autorização federal aplicável'], legalBasis:['RICMS/SC Anexo 2 art. 3 XX','Convênio ICMS 91/91'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XXI-CEV-TSE', article:'Anexo 2 art. 3 XXI', status:'mapped_rule', productCriteria:['CEV, partes, peças e acessórios'], beneficiaryCriteria:['TSE'], operationCriteria:['aquisição direta'], federalCondition:['isenção/alíquota zero de II ou IPI'], legalBasis:['RICMS/SC Anexo 2 art. 3 XXI','Convênio ICMS 75/97'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XXII-FUNASA-MINSAUDE', article:'Anexo 2 art. 3 XXII', status:'mapped_needs_catalog', productCriteria:['imunobiológicos, kits diagnósticos, medicamentos e inseticidas da Seção XVII do Anexo 1'], beneficiaryCriteria:['FUNASA/Ministério da Saúde e unidades indicadas'], operationCriteria:['campanhas/programas nacionais de saúde'], legalBasis:['RICMS/SC Anexo 2 art. 3 XXII','Convênio ICMS 95/98'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XXVII-PUBLIC-UNIVERSITIES', article:'Anexo 2 art. 3 XXVII', status:'mapped_needs_catalog', productCriteria:['aparelhos, máquinas, equipamentos e instrumentos','sem similar nacional'], beneficiaryCriteria:['universidades públicas/fundações educacionais públicas'], operationCriteria:['entrada para finalidade institucional'], requiresSimilarCheck:true, legalBasis:['RICMS/SC Anexo 2 art. 3 XXVII'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XXIX-RESEARCH-LAW8010', article:'Anexo 2 art. 3 XXIX', status:'mapped_needs_catalog', beneficiaryCriteria:['pesquisadores/instituições de pesquisa/universidades/organizações sociais/fundações elegíveis'], operationCriteria:['importação ao amparo da Lei federal 8.010','ensino/pesquisa científica ou tecnológica'], federalCondition:['isenção/alíquota zero de II ou IPI quando exigido'], legalBasis:['RICMS/SC Anexo 2 art. 3 XXIX','Convênio ICMS 43/02'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XXXII-PORT-GANTRY', article:'Anexo 2 art. 3 XXXII', status:'mapped_rule', productCriteria:['2 guindastes móveis portuários computadorizados, NCM 8426.41.00'], beneficiaryCriteria:['empresas portuárias dos portos de Itajaí/São Francisco do Sul'], operationCriteria:['aparelhamento portuário','sem similar nacional'], requiresSimilarCheck:true, legalBasis:['RICMS/SC Anexo 2 art. 3 XXXII','Convênio ICMS 56/02'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XXXIX-ROTARY-RESCUE', article:'Anexo 2 art. 3 XXXIX', status:'mapped_rule', productCriteria:['sistema de resgate hidráulico Webert Vario SPS 400, NCM 8467.89.00'], beneficiaryCriteria:['Rotary Club de Timbó/SC'], operationCriteria:['uso em resgate de acidentes'], legalBasis:['RICMS/SC Anexo 2 art. 3 XXXIX','Convênio ICMS 91/04'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XL-REPORTO', article:'Anexo 2 art. 3 XL', status:'mapped_needs_catalog', productCriteria:['bens da Seção XXX do Anexo 1','sem similar nacional'], beneficiaryCriteria:['empresa beneficiada pelo REPORTO'], operationCriteria:['utilização exclusiva em porto localizado em SC','carga/descarga/movimentação'], federalCondition:['desoneração integral dos tributos federais conforme Lei 11.033/2004'], requiresSimilarCheck:true, legalBasis:['RICMS/SC Anexo 2 art. 3 XL','Convênio ICMS 28/05'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XLI-PRIVATE-HOSPITAL', article:'Anexo 2 art. 3 XLI', status:'mapped_needs_catalog', productCriteria:['equipamento médico-hospitalar','sem similar nacional'], beneficiaryCriteria:['clínica/hospital'], operationCriteria:['entrada direta'], requiresAuthorization:true, requiresSimilarCheck:true, specialConditions:['compensação do benefício mediante prestação de serviços de saúde conforme regras do artigo','reconhecimento caso a caso'], legalBasis:['RICMS/SC Anexo 2 art. 3 XLI','Convênio ICMS 05/98'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XLII-RAIL', article:'Anexo 2 art. 3 XLII', status:'mapped_rule', productCriteria:['locomotiva diesel-elétrica >3.000 HP NCM 8602.10.00','trilho NCM 7302.10.10','sem similar nacional'], operationCriteria:['prestação de serviço de transporte ferroviário de cargas'], federalCondition:['desoneração integral do II'], requiresSimilarCheck:true, legalBasis:['RICMS/SC Anexo 2 art. 3 XLII','Convênio ICMS 32/06'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-XLIII-HUMAN-RESEARCH', article:'Anexo 2 art. 3 XLIII', status:'mapped_needs_catalog', productCriteria:['medicamentos/reagentes Seção XXXIII','kits laboratoriais','equipamentos/partes/peças'], operationCriteria:['pesquisa em seres humanos para desenvolvimento de medicamentos'], specialConditions:['registro ANVISA ou aprovação CEP quando dispensado','desoneração PIS/Cofins','desoneração II/IPI','similaridade quando exigida'], requiresSimilarCheck:true, legalBasis:['RICMS/SC Anexo 2 art. 3 XLIII','Convênio ICMS 09/07'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
  { id:'SC-EX-ART3-LXVIII-DIAGNOSTIC-KITS', article:'Anexo 2 art. 3 LXVIII', status:'mapped_needs_catalog', productCriteria:['placas-teste e soluções diluentes para kits diagnósticos especificados','sem similar nacional'], operationCriteria:['montagem de kits para diagnóstico de doenças listadas'], specialConditions:['informação fiscal específica na NF-e'], requiresSimilarCheck:true, legalBasis:['RICMS/SC Anexo 2 art. 3 LXVIII','Convênio ICMS 128/19','Lei 18.810/2023'], source:'https://legislacao.sef.sc.gov.br/html/regulamentos/icms/ricms_01_02.htm' },
];

export const SC_IMPORT_EXEMPTION_COVERAGE_NOTE =
  'A matriz deve continuar sendo completada até todos os incisos vigentes do Anexo 2 art. 3 e suas listas do Anexo 1 estarem individualizados, com vigência e condições. Incisos revogados/expirados não devem ser tratados como elegíveis.';
