export const STATE_GENERAL_ICMS_CONTRACT = "importafacil-state-general-icms-v1" as const;
export type GeneralStateIcmsRule = { uf: string; ratePercent: number; scope: "general_rate_only"; effectiveFrom: string; legalBasis: readonly string[]; sourceUrls: readonly string[]; warning: string };
export const STATE_GENERAL_ICMS_RULES: readonly GeneralStateIcmsRule[] = [
  { uf: "ES", ratePercent: 17, scope: "general_rate_only", effectiveFrom: "2022-07-01", legalBasis: ["RICMS/ES (Decreto 1.090-R/2002), art. 71, I, a e b", "Lei Complementar 87/1996 — base geral do ICMS-importação"], sourceUrls: ["https://www2.sefaz.es.gov.br/LegislacaoOnline/lpext.dll/InfobaseLegislacaoOnline/ricms%20-%20dec%201090-r/02%20-%20t%EF%BF%BDtulo%20i/17%20-%20cap%20viii.htm?2.0=&f=templates&fn=document-frame.htm"], warning: "Escopo inicial de ES: aplica somente a alíquota geral de 17% do ICMS-importação. Benefícios, reduções, isenções, ST, regimes especiais e alíquotas específicas por produto não são avaliados nesta etapa." },
  { uf: "PE", ratePercent: 20.5, scope: "general_rate_only", effectiveFrom: "2024-01-01", legalBasis: ["Lei/PE 15.730/2016, art. 15, VII", "Lei Complementar 87/1996 — base geral do ICMS-importação"], sourceUrls: ["https://www.sefaz.pe.gov.br/Legislacao/Tributaria/Documents/legislacao/Leis_Tributarias/2016/Lei15730_2016.htm"], warning: "Escopo inicial de PE: aplica somente a alíquota geral de 20,5% do ICMS-importação. FECEP, PRODEPE, PRODEAUTO, benefícios, reduções, isenções, ST, regimes especiais e alíquotas específicas por produto não são avaliados nesta etapa." },
  { uf: "PR", ratePercent: 19.5, scope: "general_rate_only", effectiveFrom: "2024-03-18", legalBasis: ["Lei/PR 11.580/1996, art. 14, VIII, com redação da Lei 21.850/2023", "RICMS/PR (Decreto 7.871/2017), art. 17, V", "Lei Complementar 87/1996 — base geral do ICMS-importação"], sourceUrls: ["https://www.legislacao.pr.gov.br/legislacao/listarAtosAno.do?action=exibir&codAto=278020&codItemAto=1778633"], warning: "Escopo inicial de PR: aplica somente a alíquota geral de 19,5% do ICMS-importação. Diferimentos, benefícios, reduções, isenções, ST, regimes especiais e alíquotas específicas por produto/importação não são avaliados nesta etapa." },
  { uf: "RO", ratePercent: 19.5, scope: "general_rate_only", effectiveFrom: "2024-01-12", legalBasis: ["Lei/RO 688/1996, art. 27, I, c, com redação da Lei 5.634/2023", "Lei Complementar 87/1996 — base geral do ICMS-importação"], sourceUrls: ["https://legislacao.sefin.ro.gov.br/detalhe?lei=2137"], warning: "Escopo inicial de RO: aplica somente a alíquota geral de 19,5% do ICMS-importação. FECOEP, benefícios, incentivos, reduções, isenções, ST, regimes especiais e alíquotas específicas permanecem fora do escopo." },
  { uf: "SP", ratePercent: 18, scope: "general_rate_only", effectiveFrom: "2016-02-23", legalBasis: ["RICMS/SP (Decreto 45.490/2000), art. 52, I", "RICMS/SP (Decreto 45.490/2000), art. 37, IV", "RICMS/SP (Decreto 45.490/2000), art. 49"], sourceUrls: ["https://legislacao.fazenda.sp.gov.br/Paginas/art052.aspx", "https://legislacao.fazenda.sp.gov.br/Paginas/art037.aspx"], warning: "Escopo inicial de SP: aplica somente a alíquota geral de 18% do ICMS-importação. Benefícios, reduções, isenções, ST, regimes especiais e alíquotas específicas por produto não são avaliados nesta etapa." },
];
export function resolveGeneralStateIcmsRule(uf: string): GeneralStateIcmsRule | null { const normalized = String(uf ?? "").trim().toUpperCase(); return STATE_GENERAL_ICMS_RULES.find((rule) => rule.uf === normalized) ?? null; }
