export const STATE_GENERAL_ICMS_CONTRACT = "importafacil-state-general-icms-v1" as const;
export type GeneralStateIcmsRule = { uf: string; ratePercent: number; scope: "general_rate_only"; effectiveFrom: string; legalBasis: readonly string[]; sourceUrls: readonly string[]; warning: string };
export const STATE_GENERAL_ICMS_RULES: readonly GeneralStateIcmsRule[] = [
  { uf: "ES", ratePercent: 17, scope: "general_rate_only", effectiveFrom: "2022-07-01", legalBasis: ["RICMS/ES (Decreto 1.090-R/2002), art. 71, I, a e b", "Lei Complementar 87/1996 — base geral do ICMS-importação"], sourceUrls: ["https://www2.sefaz.es.gov.br/LegislacaoOnline/lpext.dll/InfobaseLegislacaoOnline/ricms%20-%20dec%201090-r/02%20-%20t%EF%BF%BDtulo%20i/17%20-%20cap%20viii.htm?2.0=&f=templates&fn=document-frame.htm"], warning: "Escopo inicial de ES: aplica somente a alíquota geral de 17% do ICMS-importação. Benefícios, reduções, isenções, ST, regimes especiais e alíquotas específicas por produto não são avaliados nesta etapa." },
  { uf: "MG", ratePercent: 18, scope: "general_rate_only", effectiveFrom: "2023-07-01", legalBasis: ["Lei/MG 6.763/1975, art. 12, I, d", "RICMS/MG 2023 (Decreto 48.589/2023), Anexo I, Parte 1, item 7"], sourceUrls: ["https://www.fazenda.mg.gov.br/empresas/legislacao_tributaria/leis/l6763_1975_02.html"], warning: "Escopo inicial de MG: aplica somente a alíquota geral de 18% do ICMS-importação. Benefícios, reduções, isenções, diferimentos, ST, regimes especiais, adicionais e alíquotas específicas por produto não são avaliados nesta etapa." },
  { uf: "MS", ratePercent: 17, scope: "general_rate_only", effectiveFrom: "2007-12-21", legalBasis: ["Lei/MS 1.810/1997, art. 41, III, a — 17% nas operações internas e nas importações, ressalvadas alíquotas específicas", "Lei Complementar 87/1996 — base geral do ICMS-importação"], sourceUrls: ["https://aacpdappls.net.ms.gov.br/appls/legislacao/serc/legato.nsf/23b657614c182061042579c80053770d/9b9e5fd2565751de042579cf004d33a6"], warning: "Escopo inicial de MS: aplica somente a alíquota geral de 17% do ICMS-importação. FECOMP, benefícios, reduções, isenções, diferimentos, ST, regimes especiais e alíquotas específicas permanecem fora do escopo." },
  { uf: "MT", ratePercent: 17, scope: "general_rate_only", effectiveFrom: "2016-01-01", legalBasis: ["Lei/MT 7.098/1998, art. 14, I, c — 17% nas importações de mercadorias ou bens do exterior", "RICMS/MT, art. 95, I, c"], sourceUrls: ["https://www.sefaz.mt.gov.br/legislacao/home.aspx", "https://app1.sefaz.mt.gov.br/04256E4C004D9CE4/BDFDF560841CF35E04256CA7004FCD3E/962C500B8C1F7A4484257673004ABAB0"], warning: "Escopo inicial de MT: aplica somente a alíquota geral de 17% do ICMS-importação. FETHAB/FECP quando aplicável, benefícios, reduções, isenções, diferimentos, ST, regimes especiais e alíquotas específicas permanecem fora do escopo." },
  { uf: "PE", ratePercent: 20.5, scope: "general_rate_only", effectiveFrom: "2024-01-01", legalBasis: ["Lei/PE 15.730/2016, art. 15, VII", "Lei Complementar 87/1996 — base geral do ICMS-importação"], sourceUrls: ["https://www.sefaz.pe.gov.br/Legislacao/Tributaria/Documents/legislacao/Leis_Tributarias/2016/Lei15730_2016.htm"], warning: "Escopo inicial de PE: aplica somente a alíquota geral de 20,5% do ICMS-importação. FECEP, PRODEPE, PRODEAUTO, benefícios, reduções, isenções, ST, regimes especiais e alíquotas específicas por produto não são avaliados nesta etapa." },
  { uf: "PR", ratePercent: 19.5, scope: "general_rate_only", effectiveFrom: "2024-03-18", legalBasis: ["Lei/PR 11.580/1996, art. 14, VIII, com redação da Lei 21.850/2023", "Lei Complementar 87/1996 — base geral do ICMS-importação"], sourceUrls: ["https://www.legislacao.pr.gov.br/legislacao/listarAtosAno.do?action=exibir&codAto=278020&codItemAto=1778633"], warning: "Escopo inicial de PR: aplica somente a alíquota geral de 19,5% do ICMS-importação. Diferimentos, benefícios, reduções, isenções, ST, regimes especiais e alíquotas específicas por produto/importação não são avaliados nesta etapa." },
  { uf: "RS", ratePercent: 17, scope: "general_rate_only", effectiveFrom: "2022-01-01", legalBasis: ["Lei/RS 8.820/1989, art. 12 — alíquota modal de 17% nas demais operações", "Lei/RS 8.820/1989, art. 25, II — aplicação da alíquota interna na importação do exterior"], sourceUrls: ["https://receita.fazenda.rs.gov.br/conteudo/16309/governo-anuncia-avancos-historicos-com-a-loa-2022-e-reafirma-fim-das-aliquotas-majoradas-de-icms", "https://receita.fazenda.rs.gov.br/servicos-a-empresas/servicos?servico=1802"], warning: "Escopo inicial do RS: aplica somente a alíquota geral de 17% do ICMS-importação. AMPARA/RS quando aplicável, benefícios, reduções, isenções, diferimentos, ST, sistemas especiais de pagamento, regimes especiais e alíquotas específicas permanecem fora do escopo." },
  { uf: "RO", ratePercent: 19.5, scope: "general_rate_only", effectiveFrom: "2024-01-12", legalBasis: ["Lei/RO 688/1996, art. 27, I, c, com redação da Lei 5.634/2023", "Lei Complementar 87/1996 — base geral do ICMS-importação"], sourceUrls: ["https://legislacao.sefin.ro.gov.br/detalhe?lei=2137"], warning: "Escopo inicial de RO: aplica somente a alíquota geral de 19,5% do ICMS-importação. FECOEP, benefícios, incentivos, reduções, isenções, ST, regimes especiais e alíquotas específicas permanecem fora do escopo." },
  { uf: "SP", ratePercent: 18, scope: "general_rate_only", effectiveFrom: "2016-02-23", legalBasis: ["RICMS/SP (Decreto 45.490/2000), art. 52, I", "RICMS/SP (Decreto 45.490/2000), art. 37, IV", "RICMS/SP (Decreto 45.490/2000), art. 49"], sourceUrls: ["https://legislacao.fazenda.sp.gov.br/Paginas/art052.aspx", "https://legislacao.fazenda.sp.gov.br/Paginas/art037.aspx"], warning: "Escopo inicial de SP: aplica somente a alíquota geral de 18% do ICMS-importação. Benefícios, reduções, isenções, ST, regimes especiais e alíquotas específicas por produto não são avaliados nesta etapa." },
];
export function resolveGeneralStateIcmsRule(uf: string): GeneralStateIcmsRule | null { const normalized = String(uf ?? "").trim().toUpperCase(); return STATE_GENERAL_ICMS_RULES.find((rule) => rule.uf === normalized) ?? null; }
