"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { supabase } from "../../../lib/supabase";
import { savedSimulationKind, type SavedSimulationRecord } from "../../../lib/simulation-record";

const br=(n:number)=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const pct=(n:number)=>`${Number(n||0).toLocaleString("pt-BR",{maximumFractionDigits:2})}%`;
const labels:Record<string,string>={quantity:"Quantidade",fobUsd:"FOB unitário (US$)",fx:"Câmbio (R$/US$)",freightUsd:"Frete internacional (US$)",insuranceUsd:"Seguro internacional (US$)",otherBrl:"Outras despesas (R$)",ii:"II (%)",ipi:"IPI (%)",pis:"PIS (%)",cofins:"COFINS (%)",icms:"ICMS (%)",margin:"Margem desejada (%)"};

export default function SimulationDetail(){
 const params=useParams<{id:string}>();const[sim,setSim]=useState<SavedSimulationRecord|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/auth";return}const{data,error}=await supabase.from("simulations").select("id,name,input,result,created_at").eq("id",params.id).eq("user_id",user.id).maybeSingle();if(error||!data)setError("Não foi possível encontrar esta simulação.");else setSim(data as SavedSimulationRecord);setLoading(false)})()},[params.id]);
 if(loading)return <main style={{padding:40}}>Carregando simulação...</main>;if(error||!sim)return <main style={page}><div style={article}><h1>Simulação não encontrada</h1><p>{error||"Esta simulação pode ter sido removida."}</p><a href="/dashboard">← Voltar ao painel</a></div></main>;
 const kind=savedSimulationKind(sim);
 return <main style={page}><div style={{maxWidth:1100,margin:"auto"}}><div style={top}><a href="/dashboard" style={{color:"#111"}}>← Meu painel</a><div style={{display:"flex",gap:8}}>{kind==="v2"&&<a href={`/relatorio?id=${sim.id}`} style={button}>Relatório</a>}<button onClick={()=>window.print()} style={button}>Imprimir / Salvar PDF</button></div></div><article style={article}><small style={{letterSpacing:1,color:"#777"}}>IMPORTAFÁCIL · {kind==="v2"?"SIMULATION V2":"SIMULAÇÃO"}</small><h1 style={{fontSize:38,margin:"8px 0"}}>{sim.name||"Simulação de importação"}</h1><p style={{color:"#777"}}>Criada em {new Date(sim.created_at).toLocaleString("pt-BR")}</p>{kind==="v2"?<V2Result sim={sim}/>:kind==="sc"?<SCResult sim={sim}/>:<LegacyResult sim={sim}/>}</article></div></main>;
}

function V2Result({sim}:{sim:SavedSimulationRecord}){const r=sim.result,s=r.summary;return <><div style={{marginTop:24,padding:16,borderRadius:12,background:r.status==="calculated"?"#eef8f0":"#fff7df"}}><b>Status: {String(r.status)}</b>{r.attentionPoints?.length>0&&<ul>{r.attentionPoints.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul>}</div>{s&&<><h2 style={{marginTop:30}}>Resumo executivo</h2><div style={grid}>{[["Mercadorias",s.merchandiseBrl],["Valor aduaneiro",s.customsValueBrl],["Tributos de importação",s.importTaxesBrl],["Defesa comercial",s.defenseCommercialBrl],["Economia ICMS-importação",s.icmsImportSavingsBrl],["Custo nacionalizado",s.landedCostBrl],["Receita na margem alvo",s.targetRevenueBrl],["Lucro estimado",s.estimatedProfitBrl]].map(([a,b])=><Metric key={String(a)} label={String(a)} value={br(Number(b))}/>)}</div><h2 style={{marginTop:32}}>Itens</h2><div style={{overflowX:"auto"}}><table style={table}><thead><tr><th style={th}>Item</th><th style={th}>NCM</th><th style={th}>Status</th><th style={th}>II</th><th style={th}>IPI</th><th style={th}>Custo/un.</th><th style={th}>Margem</th><th style={th}>Preço alvo/un.</th></tr></thead><tbody>{(r.items||[]).map((x:any)=><tr key={x.itemId}><td style={td}>{x.name}</td><td style={td}>{x.ncm}</td><td style={td}>{x.status}</td><td style={td}>{pct(x.federal?.ii?.rate)}</td><td style={td}>{pct(x.federal?.ipi?.rate)}</td><td style={td}>{br(x.commercial?.breakEvenPricePerUnitBrl)}</td><td style={td}>{pct(x.commercial?.targetMarginPercent)}</td><td style={td}>{br(x.commercial?.targetSalePricePerUnitBrl)}</td></tr>)}</tbody></table></div></>}<h2 style={{marginTop:32}}>Premissas</h2><Premises input={sim.input}/><Disclaimer/></>}
function SCResult({sim}:{sim:SavedSimulationRecord}){const r=sim.result;return <><h2 style={{marginTop:30}}>Resultado da operação</h2><div style={grid}>{[["Valor aduaneiro",r.totalCustomsValue],["Despesas rateadas",r.totalAllocatedExpenses],["Tributos normais",r.totalNormalTaxes],["Economia ICMS-importação",r.totalImportICMSSavings],["Custo antes do benefício",r.totalLandedCostBeforeBenefit],["Custo final",r.totalLandedCostAfterBenefit]].map(([a,b])=><Metric key={String(a)} label={String(a)} value={br(Number(b))}/>)}</div><h2 style={{marginTop:32}}>Premissas</h2><Premises input={sim.input}/><Disclaimer/></>}
function LegacyResult({sim}:{sim:SavedSimulationRecord}){return <><h2 style={{marginTop:30}}>Resultado legado</h2><div style={grid}>{[["Custo total",sim.result.total],["Custo unitário",sim.result.unit],["Preço mínimo",sim.result.sale],["Lucro estimado",sim.result.profit],["Impostos",sim.result.tax]].map(([a,b])=><Metric key={String(a)} label={String(a)} value={br(Number(b))}/>)}</div><h2 style={{marginTop:32}}>Premissas</h2><div style={grid}>{Object.entries(sim.input).map(([key,value])=><div key={key} style={metric}><small style={{color:"#777"}}>{labels[key]||key}</small><div style={{fontWeight:700,marginTop:4}}>{typeof value==="number"?value.toLocaleString("pt-BR"):String(value)}</div></div>)}</div><Disclaimer/></>}
function Premises({input}:{input:Record<string,any>}){return <div style={grid}>{Object.entries(input).filter(([k])=>k!=="items"&&k!=="expenses").map(([k,v])=><div key={k} style={metric}><small style={{color:"#777"}}>{k}</small><div style={{fontWeight:700,marginTop:4}}>{typeof v==="number"?v.toLocaleString("pt-BR"):String(v)}</div></div>)}</div>}
function Metric({label,value}:{label:string;value:string}){return <div style={metric}><small style={{color:"#777"}}>{label}</small><div style={{fontSize:19,fontWeight:800,marginTop:5}}>{value}</div></div>}
function Disclaimer(){return <div style={{marginTop:28,padding:18,borderRadius:12,background:"#f7f7f4",color:"#555"}}>Os valores são estimativos. Valide NCM, tratamento tributário, despesas e demais premissas antes de comprometer capital.</div>}
const page={minHeight:"100vh",background:"#f7f7f4",padding:"40px 24px"} as const;const article={background:"white",padding:36,borderRadius:18,border:"1px solid #e5e5df"} as const;const top={display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24,gap:12} as const;const button={padding:"10px 15px",borderRadius:9,border:"1px solid #ccc",background:"white",cursor:"pointer",color:"#111",textDecoration:"none"} as const;const grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12} as const;const metric={padding:16,border:"1px solid #eee",borderRadius:12} as const;const table={width:"100%",borderCollapse:"collapse"} as const;const th:React.CSSProperties={textAlign:"left",padding:"10px 8px",borderBottom:"1px solid #ddd",fontSize:13,color:"#666"};const td:React.CSSProperties={padding:"11px 8px",borderBottom:"1px solid #eee"};
