"use client";
import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
import { savedSimulationComparable, type SavedSimulationRecord } from "../../lib/simulation-record";
const br=(n:number)=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function Relatorio(){
 const[sim,setSim]=useState<SavedSimulationRecord|null>(null);const[plan,setPlan]=useState("FREE");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/auth";return}const{data:p}=await supabase.from("profiles").select("plan").eq("id",user.id).maybeSingle();setPlan(p?.plan||"FREE");const id=new URLSearchParams(location.search).get("id");let q=supabase.from("simulations").select("id,name,input,result,created_at").eq("user_id",user.id);if(id)q=q.eq("id",id);const{data}=id?await q.maybeSingle():await q.order("created_at",{ascending:false}).limit(20);const candidates=(Array.isArray(data)?data:data?[data]:[]) as SavedSimulationRecord[];const chosen=candidates.find(savedSimulationComparable)||null;if(!chosen)setError("Nenhuma Simulation V2 calculada foi encontrada para gerar o relatório.");setSim(chosen);setLoading(false)})()},[]);
 if(loading)return <main style={{padding:40}}>Carregando relatório...</main>;if(plan==="FREE")return <main style={page}><div style={locked}><small style={{letterSpacing:1,color:"#777"}}>RECURSO PRO</small><h1 style={{fontSize:40,margin:"10px 0"}}>Relatório executivo da Simulation V2.</h1><p style={{fontSize:18,lineHeight:1.6,color:"#666"}}>Consolide custo nacionalizado, tributos, defesa comercial, margem e pontos de atenção em um documento pronto para decisão.</p><a href="/upgrade" style={primary}>Conhecer o PRO</a></div></main>;if(error||!sim)return <main style={page}><div style={locked}><h1>Relatório indisponível</h1><p>{error}</p><a href="/dashboard">← Meu painel</a></div></main>;
 const r=sim.result,s=r.summary;
 return <main style={page}><div style={{maxWidth:980,margin:"auto"}}><div style={top}><a href="/dashboard" style={{color:"#111"}}>← Meu painel</a><button onClick={()=>window.print()} style={button}>Imprimir / Salvar PDF</button></div><article style={report}><small style={{letterSpacing:1,color:"#777"}}>IMPORTAFÁCIL · RELATÓRIO EXECUTIVO V2</small><h1 style={{fontSize:38,margin:"8px 0"}}>{sim.name||"Simulation V2"}</h1><p style={{color:"#777"}}>Simulação criada em {new Date(sim.created_at).toLocaleString("pt-BR")}</p><div style={{margin:"22px 0",padding:15,borderRadius:12,background:r.status==="calculated"?"#eef8f0":"#fff7df"}}><b>Status: {String(r.status)}</b></div><h2>Resumo financeiro</h2><div style={grid}>{[["Mercadorias",s.merchandiseBrl],["Valor aduaneiro",s.customsValueBrl],["Tributos de importação",s.importTaxesBrl],["Defesa comercial",s.defenseCommercialBrl],["Economia ICMS-importação",s.icmsImportSavingsBrl],["Capital/custo nacionalizado",s.landedCostBrl],["Receita na margem alvo",s.targetRevenueBrl],["Lucro estimado",s.estimatedProfitBrl]].map(([a,b])=><Metric key={String(a)} label={String(a)} value={br(Number(b))}/>)}</div><h2 style={{marginTop:30}}>Itens</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={th}>Item</th><th style={th}>NCM</th><th style={th}>Origem</th><th style={th}>Custo/un.</th><th style={th}>Margem</th><th style={th}>Preço alvo/un.</th></tr></thead><tbody>{(r.items||[]).map((x:any)=><tr key={x.itemId}><td style={td}>{x.name}</td><td style={td}>{x.ncm}</td><td style={td}>{x.origin}</td><td style={td}>{br(x.commercial?.breakEvenPricePerUnitBrl)}</td><td style={td}>{Number(x.commercial?.targetMarginPercent||0).toLocaleString("pt-BR")}%</td><td style={td}>{br(x.commercial?.targetSalePricePerUnitBrl)}</td></tr>)}</tbody></table></div>{r.attentionPoints?.length>0&&<><h2 style={{marginTop:30}}>Pontos de atenção</h2><div style={{padding:18,borderRadius:12,background:"#fff7df"}}><ul>{r.attentionPoints.map((x:string,i:number)=><li key={i} style={{marginBottom:6}}>{x}</li>)}</ul></div></>}<h2 style={{marginTop:30}}>Conclusão</h2><p style={{lineHeight:1.7,color:"#444"}}>Este relatório reproduz o resultado salvo da Simulation V2. Nenhuma alíquota ou benefício é recalculado nesta tela. Preço de equilíbrio, margem e lucro partem do custo nacionalizado e não incorporam automaticamente os efeitos tributários da venda.</p></article></div></main>;
}
function Metric({label,value}:{label:string;value:string}){return <div style={metric}><small style={{color:"#777"}}>{label}</small><div style={{fontSize:21,fontWeight:800,marginTop:5}}>{value}</div></div>}
const page={minHeight:"100vh",background:"#f7f7f4",padding:"40px 24px"} as const;const locked={maxWidth:760,margin:"auto",background:"white",borderRadius:22,padding:42,border:"1px solid #e5e5df"} as const;const primary={display:"inline-block",padding:"13px 18px",background:"#111",color:"white",borderRadius:10,textDecoration:"none",fontWeight:700} as const;const top={display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24} as const;const button={padding:"10px 15px",borderRadius:9,border:"1px solid #ccc",background:"white",cursor:"pointer"} as const;const report={background:"white",padding:42,borderRadius:18,border:"1px solid #e5e5df"} as const;const grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12} as const;const metric={padding:18,border:"1px solid #eee",borderRadius:12} as const;const th:React.CSSProperties={textAlign:"left",padding:10,borderBottom:"1px solid #ddd",fontSize:13,color:"#666"};const td:React.CSSProperties={padding:10,borderBottom:"1px solid #eee"};
