"use client";

import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

const br=(n:number)=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

type Sim={id:string;name:string|null;input:Record<string,unknown>;result:Record<string,number>;created_at:string};

export default function Relatorio(){
 const [sim,setSim]=useState<Sim|null>(null); const [plan,setPlan]=useState("FREE"); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){location.href="/auth";return;} const {data:p}=await supabase.from("profiles").select("plan").eq("id",user.id).maybeSingle(); setPlan(p?.plan||"FREE"); const {data}=await supabase.from("simulations").select("id,name,input,result,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(1).maybeSingle(); setSim(data as Sim|null); setLoading(false);})()},[]);
 if(loading)return <main style={{padding:40}}>Carregando relatório...</main>;
 if(plan==="FREE")return <main style={{minHeight:"100vh",background:"#f7f7f4",padding:"70px 24px"}}><div style={{maxWidth:760,margin:"auto",background:"white",borderRadius:22,padding:42,border:"1px solid #e5e5df"}}><small style={{letterSpacing:1,color:"#777"}}>RECURSO PRO</small><h1 style={{fontSize:40,margin:"10px 0"}}>Relatórios profissionais de importação.</h1><p style={{fontSize:18,lineHeight:1.6,color:"#666"}}>Transforme sua simulação em um resumo executivo para compartilhar e tomar decisões.</p><div style={{margin:"28px 0",padding:22,borderRadius:16,background:"#111",color:"white"}}><b>PRO</b><p style={{opacity:.78}}>Relatórios, comparação de cenários e histórico completo.</p><strong>R$ 29,90/mês</strong></div><a href="/#pro" style={{display:"inline-block",padding:"13px 18px",background:"#111",color:"white",borderRadius:10,textDecoration:"none",fontWeight:700}}>Conhecer o PRO</a></div></main>;
 return <main style={{minHeight:"100vh",background:"#f7f7f4",padding:"40px 24px"}}><div style={{maxWidth:900,margin:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24}}><a href="/dashboard" style={{color:"#111"}}>← Meu painel</a><button onClick={()=>window.print()} style={{padding:"10px 15px",borderRadius:9,border:"1px solid #ccc",background:"white",cursor:"pointer"}}>Imprimir / Salvar PDF</button></div><article style={{background:"white",padding:42,borderRadius:18,border:"1px solid #e5e5df"}}><small style={{letterSpacing:1,color:"#777"}}>IMPORTAFÁCIL · RELATÓRIO EXECUTIVO</small><h1 style={{fontSize:38,margin:"8px 0"}}>{sim?.name||"Simulação de importação"}</h1><p style={{color:"#777"}}>Gerado em {new Date(sim?.created_at||Date.now()).toLocaleString("pt-BR")}</p><hr style={{border:0,borderTop:"1px solid #eee",margin:"28px 0"}}/><h2>Resumo financeiro</h2><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{[["Custo total",br(sim?.result.total||0)],["Custo unitário",br(sim?.result.unit||0)],["Preço mínimo",br(sim?.result.sale||0)]].map(([a,b])=><div key={a} style={{padding:18,border:"1px solid #eee",borderRadius:12}}><small style={{color:"#777"}}>{a}</small><div style={{fontSize:21,fontWeight:800,marginTop:5}}>{b}</div></div>)}</div><div style={{marginTop:24,padding:20,borderRadius:12,background:"#f7f7f4"}}><b>Lucro estimado</b><div style={{fontSize:28,fontWeight:800,marginTop:5}}>{br(sim?.result.profit||0)}</div><p style={{color:"#666",marginBottom:0}}>Os valores são estimativas baseadas nas premissas informadas e devem ser validados antes da operação.</p></div><h2 style={{marginTop:30}}>Conclusão</h2><p style={{lineHeight:1.7,color:"#444"}}>Este relatório consolida os principais indicadores da simulação para apoiar a decisão de compra e importação. Revise câmbio, tributos, despesas logísticas e demais premissas antes de comprometer capital.</p></article></div></main>;
}
