"use client";
import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
import { savedSimulationComparable, simulationStatusLabel, simulationProvenanceLabel, type SavedSimulationRecord } from "../../lib/simulation-record";
const br=(n:number)=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function Relatorio(){
 const[sim,setSim]=useState<SavedSimulationRecord|null>(null);const[plan,setPlan]=useState("FREE");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/auth";return}const{data:p}=await supabase.from("profiles").select("plan").eq("id",user.id).maybeSingle();setPlan(p?.plan||"FREE");const id=new URLSearchParams(location.search).get("id");let q=supabase.from("simulations").select("id,name,input,result,created_at,server_execution").eq("user_id",user.id);if(id)q=q.eq("id",id);const{data}=id?await q.maybeSingle():await q.eq("result->>contract","importafacil-simulation-v2").not("result->summary","is",null).order("created_at",{ascending:false}).limit(1);const candidates=(Array.isArray(data)?data:data?[data]:[]) as SavedSimulationRecord[];const chosen=candidates.find(savedSimulationComparable)||null;if(!chosen)setError("Nenhuma simulação calculada foi encontrada para gerar o relatório.");setSim(chosen);setLoading(false)})()},[]);
 if(loading)return <main className="productLoading">Carregando relatório...</main>;if(plan==="FREE")return <main className="productContentPage"><div className="productLocked"><small className="productEyebrow">RECURSO PRO</small><h1 className="productPageTitle">Relatório executivo da importação.</h1><p className="accountIntro">Consolide custo nacionalizado, tributos, defesa comercial, margem e pontos de atenção em um documento pronto para decisão.</p><a href="/upgrade" className="primaryBtn">Conhecer o PRO</a></div></main>;if(error||!sim)return <main className="productContentPage"><div className="productLocked"><h1>Relatório indisponível</h1><p>{error}</p><a href="/dashboard" className="accountBack">← Meu painel</a></div></main>;
 const r=sim.result,s=r.summary;
 return <main className="productContentPage"><div className="productContentShell"><div className="productPageTop"><a href="/dashboard" className="accountBack">← Meu painel</a><button onClick={()=>window.print()} className="secondaryBtn">Imprimir / Salvar PDF</button></div><article className="productArticle"><small className="productEyebrow">IMPORTAFÁCIL · RELATÓRIO EXECUTIVO</small><h1 className="productPageTitle">{sim.name||"Simulação de importação"}</h1><p className="productMeta">Simulação criada em {new Date(sim.created_at).toLocaleString("pt-BR")}</p><div style={{margin:"22px 0",padding:15,borderRadius:12,background:r.status==="calculated"?"#eef8f0":"#fff7df"}}><b>Status: {simulationStatusLabel(r.status)}</b></div><p>{simulationProvenanceLabel(sim)}</p><h2>Resumo financeiro</h2><div style={grid}>{[["Mercadorias",s.merchandiseBrl],["Valor aduaneiro",s.customsValueBrl],["Tributos de importação",s.importTaxesBrl],["Defesa comercial",s.defenseCommercialBrl],["Economia ICMS-importação",s.icmsImportSavingsBrl],["Capital/custo nacionalizado",s.landedCostBrl],["Receita na margem alvo",s.targetRevenueBrl],["Lucro estimado",s.estimatedProfitBrl]].map(([a,b])=><Metric key={String(a)} label={String(a)} value={br(Number(b))}/>)}</div><h2 style={{marginTop:30}}>Itens</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={th}>Item</th><th style={th}>NCM</th><th style={th}>Origem</th><th style={th}>Custo/un.</th><th style={th}>Margem</th><th style={th}>Preço alvo/un.</th></tr></thead><tbody>{(r.items||[]).map((x:any)=><tr key={x.itemId}><td style={td}>{x.name}</td><td style={td}>{x.ncm}</td><td style={td}>{x.origin}</td><td style={td}>{br(x.commercial?.breakEvenPricePerUnitBrl)}</td><td style={td}>{Number(x.commercial?.targetMarginPercent||0).toLocaleString("pt-BR")}%</td><td style={td}>{br(x.commercial?.targetSalePricePerUnitBrl)}</td></tr>)}</tbody></table></div>{r.attentionPoints?.length>0&&<><h2 style={{marginTop:30}}>Pontos de atenção</h2><div style={{padding:18,borderRadius:12,background:"#fff7df"}}><ul>{r.attentionPoints.map((x:string,i:number)=><li key={i} style={{marginBottom:6}}>{x}</li>)}</ul></div></>}<h2 style={{marginTop:30}}>Conclusão</h2><p style={{lineHeight:1.7,color:"#444"}}>Este relatório reproduz o resultado oficial salvo da simulação. Nenhuma alíquota ou benefício é recalculado nesta tela. Preço de equilíbrio, margem e lucro partem do custo nacionalizado e não incorporam automaticamente os efeitos tributários da venda.</p></article></div></main>;
}
function Metric({label,value}:{label:string;value:string}){return <div style={metric}><small style={{color:"#777"}}>{label}</small><div style={{fontSize:21,fontWeight:800,marginTop:5}}>{value}</div></div>}
const grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12} as const;const metric={padding:18,border:"1px solid #eee",borderRadius:12} as const;const th:React.CSSProperties={textAlign:"left",padding:10,borderBottom:"1px solid #ddd",fontSize:13,color:"#666"};const td:React.CSSProperties={padding:10,borderBottom:"1px solid #eee"};
