"use client";
import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
type Simulation={id:string;name:string|null;input:Record<string,unknown>;result:Record<string,number>;created_at:string};
const br=(n:number)=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function Dashboard(){
 const[email,setEmail]=useState("");const[plan,setPlan]=useState("FREE");const[items,setItems]=useState<Simulation[]>([]);const[loading,setLoading]=useState(true);const[notice,setNotice]=useState("");
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/auth";return}setEmail(user.email||"");const{data:profile}=await supabase.from("profiles").select("plan").eq("id",user.id).maybeSingle();if(profile?.plan)setPlan(profile.plan);const{data}=await supabase.from("simulations").select("id,name,input,result,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(50);setItems((data||[]) as Simulation[]);const params=new URLSearchParams(window.location.search);if(params.get("checkout")==="success")setNotice("Pagamento iniciado com sucesso. Seu plano será atualizado assim que a confirmação do Stripe chegar.");if(params.get("checkout")==="cancelled")setNotice("Checkout cancelado. Nenhuma alteração foi feita na sua conta.");setLoading(false)})()},[]);
 async function logout(){await supabase.auth.signOut();location.href="/"}const isFree=plan==="FREE",shown=isFree?items.slice(0,3):items;
 return <main style={{minHeight:"100vh",background:"#f7f7f4"}}><header style={{background:"white",borderBottom:"1px solid #e7e7e2"}}><div style={{maxWidth:1100,margin:"auto",padding:"18px 24px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><a href="/" style={{fontWeight:800,color:"#111",textDecoration:"none"}}>ImportaFácil</a><div style={{display:"flex",gap:14,alignItems:"center"}}><span style={{fontSize:13,color:"#666"}}>{email} · {plan}</span><button onClick={logout} style={{border:0,background:"transparent",cursor:"pointer"}}>Sair</button></div></div></header>
 <section style={{maxWidth:1100,margin:"auto",padding:"50px 24px"}}>{notice&&<div style={{marginBottom:20,padding:14,borderRadius:12,background:"#eef6ff",border:"1px solid #cfe3ff",color:"#174a7e"}}>{notice}</div>}<div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"end",marginBottom:30}}><div><small style={{letterSpacing:1,color:"#777"}}>MINHA CONTA</small><h1 style={{fontSize:40,margin:"8px 0"}}>Suas simulações</h1><p style={{color:"#666"}}>{isFree?"Seu plano gratuito inclui até 3 simulações salvas.":"Histórico completo das suas simulações."}</p></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><a href="/comparar" style={{padding:"12px 16px",border:"1px solid #111",color:"#111",borderRadius:10,textDecoration:"none",fontWeight:700}}>Comparar cenários</a><a href="/relatorio" style={{padding:"12px 16px",border:"1px solid #111",color:"#111",borderRadius:10,textDecoration:"none",fontWeight:700}}>Relatório</a>{isFree&&<a href="/upgrade" style={{padding:"12px 16px",background:"#111",color:"white",borderRadius:10,textDecoration:"none",fontWeight:700}}>Assinar PRO</a>}<a href="/#simulador" style={{padding:"12px 16px",background:"#111",color:"white",borderRadius:10,textDecoration:"none",fontWeight:700}}>Nova simulação</a></div></div>
 {loading?<p>Carregando...</p>:shown.length===0?<div style={{background:"white",border:"1px solid #e5e5df",borderRadius:18,padding:40}}><h2>Seu histórico está vazio.</h2><p style={{color:"#666"}}>Faça uma simulação e salve o resultado para começar.</p></div>:<div style={{display:"grid",gap:12}}>{shown.map(x=><a key={x.id} href={`/simulacao/${x.id}`} style={{textDecoration:"none",color:"inherit"}}><article style={{background:"white",border:"1px solid #e5e5df",borderRadius:16,padding:20,display:"flex",justifyContent:"space-between",gap:20,transition:"transform .15s"}}><div><b>{x.name||"Simulação de importação"}</b><small style={{display:"block",color:"#888",marginTop:5}}>{new Date(x.created_at).toLocaleString("pt-BR")}</small><small style={{display:"block",color:"#536dfe",marginTop:8,fontWeight:700}}>Abrir simulação →</small></div><div style={{textAlign:"right"}}><small style={{color:"#888"}}>Custo total</small><div style={{fontWeight:800,fontSize:20}}>{br(x.result.total)}</div></div></article></a>)}</div>}
 {isFree&&items.length>=3&&<div style={{marginTop:18,padding:18,borderRadius:14,background:"#fff7df",border:"1px solid #ead9a3"}}>Você atingiu o limite de 3 simulações do plano FREE. <a href="/upgrade" style={{fontWeight:700,color:"#111"}}>Assinar PRO</a> para liberar histórico completo.</div>}
 <div style={{marginTop:32,padding:24,borderRadius:16,background:"#111",color:"white"}}><b>{isFree?"PRO":"SEU PLANO"}</b><h2 style={{margin:"8px 0"}}>{isFree?"Mais decisões, menos planilhas.":"Você já está no plano avançado."}</h2><p style={{opacity:.75}}>{isFree?"Comparação de cenários, relatórios e histórico completo serão liberados no PRO.":"Os próximos recursos avançados serão adicionados à sua conta."}</p>{isFree&&<a href="/upgrade" style={{display:"inline-block",marginTop:8,padding:"11px 15px",borderRadius:9,background:"white",color:"#111",textDecoration:"none",fontWeight:800}}>Conhecer o PRO</a>}</div></section></main>
}